### PR TITLE
Remove single ; from exclusions list

### PR DESCRIPTION
**Pull request by MaxGiting**
Because of issue #427 I think we shouldn't remove single characters in the exclusions list. 

The exclusions were partly to improve performance. We see much greater returns (by using these exclusions) when running over multiple user agents, so on a single request this should make very little to no difference.

### CODE REVIEW

**Comment by JayBizzle** [comment]
I guess it throws up another question of whether the regex should be case sensitive? 🤔

**Comment by MaxGiting** [comment]
Yes it is worth testing case sensitive for sure.

I think it is also worth removing this from exclusions. Removing single characters has a higher likelihood of creating false positives like in the linked issue compared to removing multiple characters. Especially when as seen that single character is used as a delimiter character.

**Comment by gplumb** [comment]
As well as case insensitivity, how about a simple function that tokenizes
the input upfront, builds a string in the format that we're expecting and
then tests against that after?

This would mean that any unusual or unnecessary semicolons, colons or
whitespace placements can be normalised without breaking the regex


G

**Comment by JayBizzle** [comment]
Care to expand on this thought?

**Comment by JayBizzle** [comment]
Performance seems unaffected anyway, the test suite still take the same amount of time to run 👍 

> Because of issue #427 I think we shouldn't remove single characters in the exclusions list.
> 
> **The exclusions were partly to improve performance**. We see much greater returns (by using these exclusions) when running over multiple user agents, so on a single request this should make very little to no difference.

**Comment by gplumb** [comment]
Sorry, I missed this email. Will ping something over later in the week.

**Pull request merged**
