### PR TITLE
Ported to C#

### PR DESCRIPTION
**Pull request by nielsbosma**

### CODE REVIEW

**Comment by JayBizzle** [comment]
Thanks! Interesting.

Will close this as not really relevant for this repo, but feel free to start your own!

Thanks for sharing.

**Comment by alister** [comment]
I think the takeaway here is to split the data into a common project that could be re-used in other libraries, and then `Crawler-Detect` becomes a project that uses that data.

**Comment by nielsbosma** [comment]
I agree. The value of the work that's been done is in the regexps and this
can easily be using in other languages.

2016-03-16 13:57 GMT+01:00 Alister Bulman <notifications@github.com>:

> I think the takeaway here is to split the data into a common project that
> could be re-used in other libraries, and then Crawler-Detect becomes a
> project that uses that data.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JayBizzle/Crawler-Detect/pull/62#issuecomment-197310135>
>



-- 
*Niels Bosma*
+46 76 774 27 25 <https://si.gnatu.re/#>
niels@bosmainteractive.se
http://seotoolsforexcel.com
[image: Twitter] <https://twitter.com/nielsbosma>
[image: LinkedIn] <https://linkedin.com/in/bosmaniels>

*Bosma Interactive AB*
Lars Forssellsgata 30
Stockholm
111 52
Sweden
[image: banner] <http://seotoolsforexcel.com/>

**Comment by JayBizzle** [comment]
@alister @nielsbosma Yes, that is a great idea. Something I have considered, but not really sure how to go about it. What format should the regex's be presented in? Have you guys got any suggestions?

**Comment by alister** [comment]
I'd suggest a single 'master' format - a plain .txt file for the crawlers (one per line), and then a second file for the ignore list. For a release, run a little script to make some .JSON and a .php `var_export()` of the data that can be included directly as php code. Adding more exporters to the data-repo would be trivial.

**Comment by MaxGiting** [comment]
It has also been ported to GO here 
https://github.com/hangxin1940/crawler_detect

**Comment by windware** [comment]
There's a similar project that targets multiple languages and keeps the detection rules in yaml files. You might want to take a look on how they do it.

https://github.com/ua-parser/uap-core
https://raw.githubusercontent.com/ua-parser/uap-core/master/regexes.yaml

**Comment by JayBizzle** [comment]
@windware thanks for that. Certainly an interesting approach and will definitely look into this further soon 👍

**Comment by JayBizzle** [comment]
RAW regex output now available here https://github.com/JayBizzle/Crawler-Detect/tree/master/raw

**Pull request closed without merging**
