### PR TITLE
Add W3C Validators

### PR DESCRIPTION
**Pull request by MaxGiting**
List found at http://validator.w3.org/services

### CODE REVIEW

**Comment by JayBizzle** [comment]
Its failing against this user agent in the `devices.txt` test file

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:25.0) Gecko/20100101 Firefox/25.0 SeaMonkey/2.22 Lightning/2.7b1`

**Comment by JayBizzle** [comment]
...although i'm not sure why

**Comment by JayBizzle** [comment]
`NING\/` is matching `Lightning/2.7b1`

**Comment by MaxGiting** [comment]
Beat me to it yes it is. I'll add the version number to NING

**Comment by JayBizzle** [comment]
You could prefix the regex with a caret `^` to indicate it has to be at the start of the string

**Pull request merged**
