### PR TITLE
add crawler

### PR DESCRIPTION
**Pull request by IT-Joris**

### CODE REVIEW

**Comment by JayBizzle** [comment]
Failing test here @IT-Joris 

I think you make need to escape the brackets in `nbertaupete95(at)gmail.com`

**Comment by IT-Joris** [comment]
Hello @JayBizzle, I made the corrections on my branch.
Unfortunately the line Mozilla/5.0/Firefox/42.0 - nbertaupete95(at)gmail.com is present in the tests/devices.txt which makes the test user_agents_are_devices fail.

**Comment by JayBizzle** [comment]
Thanks, if you push those changes, ill rerun tests and get this merged 👍

**Comment by IT-Joris** [comment]
Hello @JayBizzle, as mentioned above, the tests don't work because the user agent is present in the device.txt folder. How can I fix this?

Because the user agent is considered a crawler.

**Comment by JayBizzle** [comment]
Just remove that line from `devices.txt` as you have now added it to `crawlers.txt` 👍

**Comment by IT-Joris** [comment]
The devices.txt file is read-only

**Comment by IT-Joris** [comment]
Sorry @JayBizzle, my IDE was blocking editing of the file, as it was too large, so I pushed the correction and testing successful through on my end.

**Comment by JayBizzle** [comment]
Ha, yeah, that file is fairly large 😬

**Pull request merged**
