### PR TITLE
Monit and generic New relic

### PR DESCRIPTION
**Pull request by timersys**
I added Monit monitor system and remove version from Newrelic for a non version dependant regex

### CODE REVIEW

**Comment by JayBizzle** [comment]
Have you got an example user agent for `monit`.

The monit regex will need to be more specific because it will match any word with the string `monit` in it...like `monitoring` etc

**Comment by timersys** [comment]
Right, sorry about that. 
`Monit/5.25.2`

**Comment by JayBizzle** [comment]
I suggest changing the regex to `monit\/` 👍

**Comment by timersys** [comment]
Done

**Comment by JayBizzle** [comment]
👍

**Pull request merged**
