### PR TITLE
Create a PHP 7.1 version

### PR DESCRIPTION
**Pull request by JayBizzle**

### CODE REVIEW

**Comment by Ardakilic** [comment]
It is still early to merge this for the time being I guess, because PHP5.6 is not quite deprecated yet.

https://secure.php.net/supported-versions.php

**Comment by JayBizzle** [comment]
Don't worry, this won't be getting merged, there will be 2 versions to choose from. A PHP >= 5.2 compatible version and a PHP 7 version

Version 1 will still be on par with version 2 in terms of crawler detection, and will receive the same regex updates.

**Comment by Ardakilic** [comment]
Thank you for the clarification. If this'll be in a new major version and both versions's crawler data will be in sync that's great then! Oh and let this be a chance to thank you for maintaining such a useful package 🙇

**Comment by JayBizzle** [comment]
@Ardakilic We still use PHP 5.5 and 5.6 in a lot of our production apps, so it wont be going anywhere for a long time.

And thank you for the kind words, glad you find CrawlerDetect useful.

**Comment by JayBizzle** [comment]
Oh, and here is some more info on the PHP 7 transition if your interested https://seld.be/notes/php-versions-stats-2016-2-edition

**Comment by alister** [comment]
I have to admit, I think that combining use statements looks a little ugly, and the fact you have turn off the style warnings shows that other people aren't keen on multi-use statements either.

What I will happily do though is make explicit as to what namespace is being used - even though it's a little bit of duplication, but I think it helps to clarify the code - and is therefore, IMHO, a net win.

    use Jaybizzle\CrawlerDetect\Fixtures;

    // and then use them as:
    $this->crawlers = new Fixtures\Crawlers();

**Comment by JayBizzle** [comment]
@alister Thanks for your feedback.

I have to admit, i think i agree with you about the combined use statements.

FYI, this branch is just a test bed for the first steps into the PHP 7 world. Happy for everyone's feedback.

Also, happy for pull requests on this branch.

Thanks

**Comment by JayBizzle** [comment]
Closing for now

**Pull request closed without merging**
