### PR TITLE
Added QQDownload Bot

### PR DESCRIPTION
**Pull request by JefferyHus**
--

### CODE REVIEW

**Comment by JayBizzle** [comment]
Thanks!

Do you have the full user agent that you can put in the tests here?https://github.com/JayBizzle/Crawler-Detect/blob/master/tests/crawlers.txt

**Comment by JayBizzle** [comment]
Also, there are a couple of user agents containing `QQDownload` in the `devices.txt` file that need moving to the `crawlers.txt` file. Any chance you could do that and push the changes to this PR.

That will make the tests pass.

Thanks 👍

**Comment by JefferyHus** [comment]
Sure I will I have the full User agent :+1:

**Comment by JayBizzle** [comment]
❤️

**Comment by JefferyHus** [comment]
Just wondering, if there will be any future possibility to check IPs, as I have detected plenty of bots that uses a normal user agent and therefor can't be detected, at the same time they keep pinging your domain lot.

**Comment by JayBizzle** [comment]
This is something we have been [asked before](https://github.com/JayBizzle/Crawler-Detect/issues/149) and something we have considered ourselves, but feel it is a massive undertaking to manage and keep up to date.

I you have some IP address to contribute, we may look at adding it as an experimental feature and see where we get with it...

**Comment by JefferyHus** [comment]
Sure I have plenty of IP addresses, as I have been testing around this on a website using other scanning tools, now I have a DB of IPs with user-agents and grows everyday. So I will try to see how it will be going if such feature is added to this repo. thanks

**Comment by JayBizzle** [comment]
@JefferyHus I have started putting together an experimental feature to check for IP address. I'll put this on a new branch sometime this week. Once that branch is ready, perhaps you could PR the IPs you have into that branch.

**Comment by JanKrohn-Khalibre** [comment]
As for me, I block the range 72.21.192.0 to 72.21.223.255 manually. They're the worst offenders by far...

**Comment by JayBizzle** [comment]
@JanKrohn-Khalibre Thanks, ill be sure to look into that range of IPs

**Comment by JefferyHus** [comment]
@JayBizzle okay I will be waiting as I do have a wide range of IPs.

**Comment by JayBizzle** [comment]
@JefferyHus Would you like to share your list of IPs with me now so i can do some testing. If you don't want to post here, you can email me at m@rkbee.ch

Thanks

**Comment by JefferyHus** [comment]
@JayBizzle I have sent you a list of IPs, one other thing That I have noticed is that some bots don't really send the user-agent so maybe try to check for this case ?

**Comment by JayBizzle** [comment]
Hi @JefferyHus 

I received your email, thanks!

I have put the IP checking functionality on the back burner for now, you can see the progress i made in #189 

This is not to say i won't be working on it, just that there is no deadline on the feature, if it ever happens.

We are open to PR's though 👍

**Pull request merged**
